name: clone-to-repos
description: Clone one image with multiple arcs to multiple image repos

inputs:
  platform:
    description: TODO
    required: true
  image_tag:
    description: TODO
    required: true
  main_registry:
    description: TODO
    required: true
  main_username:
    description: TODO
    required: true
  main_password:
    description: TODO
    required: true
  main_repository:
    description: TODO
    required: true

runs:
  using: "composite"
  steps:
    - name: Setup Job Variables
      shell: bash
      id: set-build-variables
      run: |
        echo "PLATFORM_DASH=$(echo ${{ inputs.platform }} | sed -e 's/\//-/g')" >> $GITHUB_OUTPUT

    - name: Set up QEMU
      uses: docker/setup-qemu-action@e81a89b1732b9c48d79cd809d8d81d79c4647a18 #pin@v2.1.0

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@8c0edbc76e98fa90f69d9a2c020dcb50019dc325 #pin@v2.2.1

    - name: Log in to Registry
      uses: redhat-actions/podman-login@632d91dfe19e1b55833cb708786bfbad2c2a0335 #pin@v3.2.0
      with:
        registry: ${{ inputs.main_registry }}
        username: ${{ inputs.main_username }}
        password: ${{ inputs.main_password }}

    - name: Build container image
      uses: docker/build-push-action@37abcedcc1da61a57767b7588cb9d03eb57e28b3 #pin@v3.3.0
      with:
        context: backstage
        file: Dockerfile
        platforms: ${{ inputs.platform }}
        provenance: false
        push: true
        tags: |
          ${{ inputs.main_registry }}/${{ inputs.main_repository }}:latest-${{ steps.set-build-variables.outputs.PLATFORM_DASH }}
          ${{ inputs.main_registry }}/${{ inputs.main_repository }}:${{ inputs.image_tag }}-${{ steps.set-build-variables.outputs.PLATFORM_DASH }}
