name: two

on:
  workflow_call:
    inputs:
      default_tag_version:
        required: true
        type: string

jobs:
  two:
    runs-on: ubuntu-latest
    steps:
      - name: two
        id: set-variables
        run: |
          echo "input:"
          echo ${{ inputs.default_tag_version }}
