name: Build
on:
  push:
    branches:
      - main
    tags:
      - v*

env:
  FOO: "boo"

jobs:
  setup:
    runs-on: ubuntu-latest
    steps:
      - name: setup
        uses: ./.github/setup
        with:
          default_tag_version: ${{ env.FOO }}
          build_platforms: "linux/amd64,linux/arm64"
          image_registry: "ghcr.io"

  build:
    runs-on: ubuntu-latest
    needs: ["setup"]
    steps:
      - name: Print
        run: |
          echo "repository_name:"
          echo ${{ needs.setup.outputs.repository_name }}
          echo "image_repository:"
          echo ${{ needs.setup.outputs.image_repository }}
          echo "image_registry:"
          echo ${{ needs.setup.outputs.image_registry }}
          echo "image_tag:"
          echo ${{ needs.setup.outputs.image_tag }}
          echo "dist_matrix:"
          echo ${{ needs.setup.outputs.dist_matrix }}
          echo "image_platform_tags:"
          echo ${{ needs.setup.outputs.image_platform_tags }}

  anotherone:
    needs: ["setup"]
    uses: ./.github/workflows/anotherone.yaml
    with:
      default_tag_version: ${{ needs.setup.outputs.repository_name }}
