name: Build
on:
  push:
    branches:
      - main
    tags:
      - v*

env:
  DEFAULT_TAG_VERSION: "latest"
  BUILD_PLATFORMS: "linux/amd64,linux/arm64"
  IMAGE_REGISTRY: "ghcr.io"

jobs:
  setup:
    uses: .github/workflows/setup.yaml@main
    with:
      default_tag_version: ${DEFAULT_TAG_VERSION}
      build_platforms: ${BUILD_PLATFORMS}
      image_registry: ${IMAGE_REGISTRY}

  build:
    runs-on: ubuntu-latest
    needs: ["setup"]
    steps:
      - name: Print
        run: |
          echo "repository_name:"
          echo ${{ needs.setup.outputs.repository_name }}
          echo "\necho "image_repository:""
          echo ${{ needs.setup.outputs.image_repository }}
          echo "\necho "image_tag:""
          echo ${{ needs.setup.outputs.image_tag }}
          echo "\necho "dist_matrix:""
          echo ${{ needs.setup.outputs.dist_matrix }}
          echo "\necho "image_platform_tags:""
          echo ${{ needs.setup.outputs.image_platform_tags }}
