# name: Build
# on:
#   push:
#     branches:
#       - main
#       - test
#     tags:
#       - v*

# jobs:
#   setup:
#     uses: ./.github/workflows/setup.yaml
#     with:
#       default_tag_version: "latest"
#       build_platforms: "linux/amd64,linux/arm64"
#       image_registries: "ghcr.io,quay.io"

#   build:
#     runs-on: ubuntu-latest
#     needs: ["setup"]
#     strategy:
#       matrix:
#         platform: ${{ fromJson(needs.setup.outputs.dist_matrix) }}
#         registry: ${{ fromJson(needs.setup.outputs.registry_matrix) }}
#         include:
#           - registry: ghcr.io
#             username: GHCR_NAME
#             password: GITHUB_TOKEN
#           - registry: quay.io
#             username: QUAY_NAME
#             password: QUAY_TOKEN
#     steps:
#       - name: Setup Job Variables
#         id: set-build-variables
#         run: |
#           echo "PLATFORM_OS=$(echo ${{ matrix.platform }} |  cut -d/ -f1)" >> $GITHUB_OUTPUT
#           echo "PLATFORM_ARCH=$(echo ${{ matrix.platform }} |  cut -d/ -f2)" >> $GITHUB_OUTPUT

#       - name: checkout repo
#         uses: actions/checkout@755da8c3cf115ac066823e79a1e1788f8940201b # pin@v3

#       - name: Set up QEMU
#         uses: docker/setup-qemu-action@e81a89b1732b9c48d79cd809d8d81d79c4647a18 #pin@v2.1.0

#       - name: Set up Docker Buildx
#         uses: docker/setup-buildx-action@8c0edbc76e98fa90f69d9a2c020dcb50019dc325 #pin@v2.2.1

#       - name: Docker Login
#         uses: docker/login-action@f4ef78c080cd8ba55a85445d5b36e214a81df20a #pin@v2.1.0
#         with:
#           registry: ${{ matrix.registry }}
#           username: ${{ vars[matrix.username] }}
#           password: ${{ secrets[matrix.password] }}
