# name: Build
# on:
#   push:
#     branches:
#       - main
#     tags:
#       - v*

# jobs:
#   setup:
#     uses: ./.github/workflows/setup.yaml
#     with:
#       default_tag_version: "latest"
#       build_platforms: "linux/amd64,linux/arm64"
#       image_registry: "ghcr.io"

#   build:
#     runs-on: ubuntu-latest
#     needs: ["setup"]
#     strategy:
#       matrix:
#         platform: ${{ fromJson(needs.setup.outputs.dist_matrix) }}
#     steps:
#       - name: Setup Job Variables
#         id: set-build-variables
#         run: |
#           echo "PLATFORM_OS=$(echo ${{ matrix.platform }} |  cut -d/ -f1)" >> $GITHUB_OUTPUT
#           echo "PLATFORM_ARCH=$(echo ${{ matrix.platform }} |  cut -d/ -f2)" >> $GITHUB_OUTPUT

#       - name: checkout repo
#         uses: actions/checkout@755da8c3cf115ac066823e79a1e1788f8940201b # pin@v3

#       - name: Set up QEMU
#         uses: docker/setup-qemu-action@e81a89b1732b9c48d79cd809d8d81d79c4647a18 #pin@v2.1.0

#       - name: Set up Docker Buildx
#         uses: docker/setup-buildx-action@8c0edbc76e98fa90f69d9a2c020dcb50019dc325 #pin@v2.2.1

#       - name: Docker Login
#         uses: docker/login-action@f4ef78c080cd8ba55a85445d5b36e214a81df20a #pin@v2.1.0
#         with:
#           registry: ${{ needs.setup.outputs.image_registry }}
#           username: ${{ github.actor }}
#           password: ${{ secrets.GITHUB_TOKEN }}

#       - uses: actions/setup-node@8c91899e586c5b171469028077307d293428b516 #pin@v3.5.1
#         with:
#           node-version: 18

#       - name: Setup git
#         run: |
#           git config --global user.name "$GITHUB_ACTOR"
#           git config --global user.email "$GITHUB_ACTOR@users.noreply.github.com"

#       # - name: Create Backstage application
#       #   run: |
#       #     echo backstage | npx @backstage/create-app
#       #     cp ./Dockerfile ./.dockerignore ./backstage/


      
#       - name: checl
#         run: |
#           echo $

#       - name: Build container image and push
#         uses: docker/build-push-action@c56af957549030174b10d6867f20e78cfd7debc5 #pin@v3.2.0
#         with:
#           context: backstage
#           file: Dockerfile
#           platforms: ${{ matrix.platform }}
#           push: true
#           tags: |
#             ${{ needs.setup.outputs.image_repository }}:latest-${{ steps.set-build-variables.outputs.PLATFORM_OS }}-${{ steps.set-build-variables.outputs.PLATFORM_ARCH }}
#             ${{ needs.setup.outputs.image_repository }}:${{ needs.setup.outputs.image_tag }}-${{ steps.set-build-variables.outputs.PLATFORM_OS }}-${{ steps.set-build-variables.outputs.PLATFORM_ARCH }}

#   process-image-manifest:
#     runs-on: ubuntu-latest
#     name: process-image-manifest
#     needs: ["setup", "build"]
#     steps:
#       - name: Log in to Registry
#         uses: redhat-actions/podman-login@632d91dfe19e1b55833cb708786bfbad2c2a0335 #pin@v3.2.0
#         with:
#           username: ${{ github.actor }}
#           password: ${{ secrets.GITHUB_TOKEN }}
#           registry: ${{ needs.setup.outputs.image_registry }}
#       - name: "Append to Bundle Image Manifest"
#         shell: bash
#         run: |
#           TAGS="latest" 

#           if [[ "${{ needs.setup.outputs.image_tag }}" != "latest" ]]; then
#             TAGS="$TAGS ${{ needs.setup.outputs.image_tag }}"
#           fi

#           for TAG in $TAGS; do \
#             echo $TAG
#             podman manifest create ${{ needs.setup.outputs.image_repository }}:$TAG
#             for PLATFORM in ${{ needs.setup.outputs.image_platform_tags }}; do \
#               echo $PLATFORM
#               podman manifest add ${{ needs.setup.outputs.image_repository }}:$TAG docker://${{ needs.setup.outputs.image_repository }}:$TAG-$PLATFORM; \
#             done
#             podman manifest push ${{ needs.setup.outputs.image_repository }}:$TAG docker://${{ needs.setup.outputs.image_repository }}:$TAG
#           done


name: Build
on:
  push:
    branches:
      - main
    tags:
      - v*

env:
  MAIN_REGISTRY: ghcr.io
  MAIN_USERNAME: ${{ github.actor }}
  MAIN_PASSWORD: ${{ github.token }}
  MAIN_REPOSITORY: ${{ github.repository }}

jobs:
  setup:
    uses: skopecky-test/.github/.github/workflows/setup.yaml
    with:
      default_tag_version: "latest"
      build_platforms: "linux/amd64,linux/arm64"

  build-images:
    runs-on: ubuntu-latest
    needs: ["setup"]
    strategy:
      matrix:
        platform: ${{ fromJson(needs.setup.outputs.dist_matrix) }}

    steps:
      - name: checkout repo
        uses: actions/checkout@755da8c3cf115ac066823e79a1e1788f8940201b # pin@v3

      - uses: actions/setup-node@8c91899e586c5b171469028077307d293428b516 #pin@v3.5.1
        with:
          node-version: 18

      - name: Create Backstage application
        run: |
          mkdir backstage
          cp ./Dockerfile ./.dockerignore ./backstage/

      - name: Do stuff
        uses: skopecky-test/.github/.github/actions/build-and-push
        with:
          platform: ${{ matrix.platform }}
          image_tag: ${{ needs.setup.outputs.image_tag }}
          context: backstage

  push-images-and-manifests:
    runs-on: ubuntu-latest
    needs: ["setup", "build-images"]
    strategy:
      matrix:
        include:
          - registry: ghcr.io
            username: ${{ github.actor }}
            password: GITHUB_TOKEN
            repository: ${{ github.repository }}
          # Define more image repositories like this:
          - registry: quay.io
            username: ${{ vars.QUAY_USERNAME }}
            password: QUAY_TOKEN
            repository: skopecky/janus-backstage-test

    steps:
      - name: checkout repo
        uses: actions/checkout@755da8c3cf115ac066823e79a1e1788f8940201b # pin@v3

      - name: Do stuff
        uses: skopecky-test/.github/.github/actions/clone-to-repos
        with:
          image_platform_tags: ${{ needs.setup.outputs.image_platform_tags }}
          image_tag: ${{ needs.setup.outputs.image_tag }}
          registry: ${{ matrix.registry }}
          username: ${{ matrix.username }}
          password: ${{ secrets[matrix.password] }}
          repository: ${{ matrix.repository }}
