name: Build
on:
  push:
    branches:
      - main
    tags:
      - v*

env:
  DEFAULT_TAG_VERSION: "latest"
  BUILD_PLATFORMS: "linux/amd64,linux/arm64"
  IMAGE_REGISTRY: "ghcr.io"

jobs:
  setup:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: setup
        id: set-variables
        uses: ./.github/actions/setup
        with:
          default_tag_version: ${{ env.DEFAULT_TAG_VERSION }}
          build_platforms: ${{ env.BUILD_PLATFORMS }}
          image_registry: ${{ env.IMAGE_REGISTRY }}
    outputs:
      repository_name: ${{ steps.set-variables.outputs.REPOSITORY_NAME }}
      image_repository: ${{ steps.set-variables.outputs.IMAGE_REPOSITORY }}
      image_registry: ${{ steps.set-variables.outputs.IMAGE_REGISTRY }}
      image_tag: ${{ steps.set-variables.outputs.IMAGE_TAG}}
      dist_matrix: ${{ steps.set-variables.outputs.DIST_MATRIX }}
      image_platform_tags: ${{ steps.set-variables.outputs.IMAGE_PLATFORM_TAGS }}

  build:
    runs-on: ubuntu-latest
    needs: ["setup"]
    steps:
      - name: Print
        run: |
          echo "repository_name:"
          echo ${{ needs.setup.outputs.repository_name }}
          echo "image_repository:"
          echo ${{ needs.setup.outputs.image_repository }}
          echo "image_registry:"
          echo ${{ needs.setup.outputs.image_registry }}
          echo "image_tag:"
          echo ${{ needs.setup.outputs.image_tag }}
          echo "dist_matrix:"
          echo ${{ needs.setup.outputs.dist_matrix }}
          echo "image_platform_tags:"
          echo ${{ needs.setup.outputs.image_platform_tags }}

  anotherone:
    needs: ["setup"]
    uses: ./.github/workflows/anotherone.yaml
    with:
      default_tag_version: ${{ needs.setup.outputs.repository_name }}
