name: Build
on:
  push:
    branches:
      - main
    tags:
      - v*

env:
  DEFAULT_TAG_VERSION: "latest"
  BUILD_PLATFORMS: "linux/amd64,linux/arm64"
  IMAGE_REGISTRY: "ghcr.io"

jobs:
  setup:
    uses: ./.github/workflows/setup.yaml
    with:
      default_tag_version: ${{ env.DEFAULT_TAG_VERSION }}
      build_platforms: ${{ env.BUILD_PLATFORMS }}
      image_registry: ${{ env.IMAGE_REGISTRY }}

  build:
    runs-on: ubuntu-latest
    needs: ["setup"]
    steps:
      - name: Print
        run: |
          echo "repository_name:"
          echo ${{ needs.setup.outputs.repository_name }}
          echo "image_repository:"
          echo ${{ needs.setup.outputs.image_repository }}
          echo "image_tag:"
          echo ${{ needs.setup.outputs.image_tag }}
          echo "dist_matrix:"
          echo ${{ needs.setup.outputs.dist_matrix }}
          echo "image_platform_tags:"
          echo ${{ needs.setup.outputs.image_platform_tags }}
