name: Build
on:
  push:
    branches:
      - main
    tags:
      - v*

env:
  TEST_ENV: "thisisatest"

jobs:
  setup:
    uses: ./.github/workflows/setup.yaml
    with:
      default_tag_version: $TEST_ENV
      build_platforms: "linux/amd64,linux/arm64"
      image_registry: $TEST_ENV

  build:
    runs-on: ubuntu-latest
    needs: ["setup"]
    steps:
      - name: Print
        run: |
          echo "repository_name:"
          echo ${{ needs.setup.outputs.repository_name }}
          echo "image_repository:"
          echo ${{ needs.setup.outputs.image_repository }}
          echo "image_registry:"
          echo ${{ needs.setup.outputs.image_registry }}
          echo "image_tag:"
          echo ${{ needs.setup.outputs.image_tag }}
          echo "dist_matrix:"
          echo ${{ needs.setup.outputs.dist_matrix }}
          echo "image_platform_tags:"
          echo ${{ needs.setup.outputs.image_platform_tags }}
