name: Build
on:
  push:
    branches:
      - main
    tags:
      - v*

env:
  DEFAULT_TAG_VERSION: "latest"
  BUILD_PLATFORMS: "linux/amd64,linux/arm64"
  IMAGE_REGISTRY: "ghcr.io"

jobs:
  setup:
    runs-on: ubuntu-latest
    steps:
      - name: Setup Workflow Variables
        id: set-variables
        run: |
          echo "REPOSITORY_NAME=$(basename $GITHUB_REPOSITORY)" >> $GITHUB_OUTPUT
          echo "IMAGE_REPOSITORY=${{ env.IMAGE_REGISTRY}}/$GITHUB_REPOSITORY" >> $GITHUB_OUTPUT
          # Set versions based on presence of tag
          if [[ "${{ github.ref }}" =~ ^refs/tags/ ]]; then
            echo "IMAGE_TAG=$(echo ${GITHUB_REF/refs\/tags\//})" >> $GITHUB_OUTPUT
          else
            echo "IMAGE_TAG=${DEFAULT_TAG_VERSION}" >> $GITHUB_OUTPUT
          fi
          # Create Distribution Matrix
          echo "DIST_MATRIX=$(echo -n "$BUILD_PLATFORMS" | jq -csR '. | split(",")')" >> $GITHUB_OUTPUT
          # Create Image Tags
          echo "IMAGE_PLATFORM_TAGS=$(echo $BUILD_PLATFORMS | sed  -e 's/,/ /g' -e 's/\//-/g')" >> $GITHUB_OUTPUT
    outputs:
      repository_name: ${{ steps.set-variables.outputs.REPOSITORY_NAME }}
      image_repository: ${{ steps.set-variables.outputs.IMAGE_REPOSITORY }}
      image_tag: ${{ steps.set-variables.outputs.IMAGE_TAG}}
      dist_matrix: ${{ steps.set-variables.outputs.DIST_MATRIX }}
      image_platform_tags: ${{ steps.set-variables.outputs.IMAGE_PLATFORM_TAGS }}

  build:
    runs-on: ubuntu-latest
    needs: ["setup"]
    steps:
      - name: Print
        run: |
          echo "repository_name:"
          echo ${{ needs.setup.outputs.repository_name }}
          echo "image_repository:"
          echo ${{ needs.setup.outputs.image_repository }}
          echo "image_tag:"
          echo ${{ needs.setup.outputs.image_tag }}
          echo "dist_matrix:"
          echo ${{ needs.setup.outputs.dist_matrix }}
          echo "image_platform_tags:"
          echo ${{ needs.setup.outputs.image_platform_tags }}
