name: Pull Request

on: pull_request

env:
  MAIN_REGISTRY: ghcr.io
  MAIN_USERNAME: ${{ github.actor }}
  MAIN_PASSWORD: ${{ github.token }}
  MAIN_REPOSITORY: ${{ github.repository }}

jobs:
  setup:
    uses: skopecky-test/.github/.github/workflows/setup.yaml@main
    with:
      default_tag_version: "latest"
      build_platforms: "linux/amd64,linux/arm64"

  build-images:
    runs-on: ubuntu-latest
    needs: ["setup"]
    strategy:
      matrix:
        platform: ${{ fromJson(needs.setup.outputs.dist_matrix) }}

    steps:
      - name: checkout repo
        uses: actions/checkout@755da8c3cf115ac066823e79a1e1788f8940201b # pin@v3

      - uses: actions/setup-node@8c91899e586c5b171469028077307d293428b516 #pin@v3.5.1
        with:
          node-version: 18

      - name: Create Backstage application
        run: |
          mkdir backstage
          cp ./Dockerfile ./.dockerignore ./backstage/

      - name: Build images
        uses: skopecky-test/.github/.github/actions/build-and-push@main
        with:
          platform: ${{ matrix.platform }}
          image_tag: ${{ needs.setup.outputs.image_tag }}
          context: backstage
          push: false
